[package]
name = "scalpel"
version = "0.1.0"
authors = ["gabhijit"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"


[dev-dependencies]
hex = "0.4"
criterion = "0.3"


[[bench]]
name = "layer3_benchmark"
harness = false


[[bench]]
name = "ipv6_display"
harness = false
