[package]
name = "scalpel"
version = "0.1.0"
authors = ["gabhijit"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = {version = "0.4", features = ["serde"]}
lazy_static = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
erased-serde = "0.3"

[dev-dependencies]
criterion = "0.3"

# Required by `cargo flamegraph`
[profile.bench]
debug = true

[[bench]]
name = "ip_dissect"
harness = false


[[bench]]
name = "ipv6_display"
harness = false

[[bench]]
name = "dns"
harness = false
